Description of fnorm
fnorm
PURPOSE
Frobenius norm of ktensor.
SYNOPSIS
function nrm = fnorm(A)
DESCRIPTION
 Frobenius norm of ktensor.
 Required input:
   A = ktensor
 Output:
   nrm = Frobenius norm
CROSS-REFERENCE INFORMATION
This function calls:
iprod Inner product of two ktensors in vector format
This function is called by:
alsi Main ALS iteration. See als.m for arguments
tenid Tensor ID.
test_als
test_getterms
test_mmm
test_mvm
test_norms
test_poswts
test_tenid
test_trncel
test_trncsval
test_vvpwm
main_run MAIN_RUN obtains the solution to the setup specified in MAIN_PROGRAM,
main_run_spectral MAIN_RUN obtains the solution to the setup specified in MAIN_PROGRAM,
test_VTOL_tensor
test_finite_horizon_hjb_backward_euler Test finite horizon hjb, backward euler
test_finite_horizon_hjb_euler Test finite horizon hjb, forward euler
test_finite_horizon_hjb_scaling Finite Horizon
test_infinite_horizon_hjb Test finite horizon hjb, backward euler
test_pdf_ND_tensor % Test Tensor Form PDF Evolution ND
test_pdf_ND_tensor_run % Test Tensor Form PDF Evolution ND
SOURCE CODE
function nrm = fnorm(A)
% Frobenius norm of ktensor.
%
% Required input:
%   A = ktensor
%
% Output:
%   nrm = Frobenius norm
  nrm = iprod(A,A);
  nrm = full(sqrt(abs(nrm)));
end