Description of knumel
knumel
PURPOSE
Number of elements in a ktensor
SYNOPSIS
function n = knumel(A)
DESCRIPTION
 Number of elements in a ktensor
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
als Rank reduction by standard ALS.
alsi Main ALS iteration. See als.m for arguments
test_k
test_krand
SOURCE CODE
function n = knumel(A)
% Number of elements in a ktensor
    n=0;
    for d=1:ndims(A)
        n = n + numel(A.U{d});
    end
end