Description of krandu
krandu
PURPOSE
Create random sparse ctd with uniformly distributed elements.
SYNOPSIS
function B=krandu(D,N,R,density)
DESCRIPTION
 Create random sparse ctd with uniformly distributed elements.
 Input:
   D = number of dimensions
   N = scalar or D-vector of dimension sizes
   R = separtion rank
   density = scalar between 0 and 1, approximate fraction of non-zeros.
 Output:
   B = a random sparse ktensor
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
test_krand
test_tenid
test_vvpwm
SOURCE CODE
function B=krandu(D,N,R,density)
% Create random sparse ctd with uniformly distributed elements.
%
% Input:
%   D = number of dimensions
%   N = scalar or D-vector of dimension sizes
%   R = separtion rank
%   density = scalar between 0 and 1, approximate fraction of non-zeros.
%
% Output:
%   B = a random sparse ktensor
    % if N is a scalar, make all dimensions of this size
    if length(N)==1
        N=N*ones(1,D);
    end
    B=cell(1,D);
    for d=1:D
        if density==1
            B{d}=2*(rand(N(d),R)-.5);
        else
            B{d}=sprand(N(d),R,density);
        end
    end
    B=ktensor(ones(R,1),B);
    % normalize and sort
    %B = arrange(B);
end