Description of trncspmat
trncspmat
PURPOSE
For a sparse matrix, truncate all elements less than delta using a mask.
SYNOPSIS
function A = trncspmat(A,delta)
DESCRIPTION
 For a sparse matrix, truncate all elements less than delta using a mask.
 There might be a better way to do this, but this way avoids having
 explicit indexing.
 Input:
   A = sparse matrix
   delta = cutoff threshold
 Ouput:
   A = truncated input
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
test_trncspmat
trncel Absolute truncation of factor matrices. All entries less than delta in
trncel2 Relative truncation of factor matrices. All entries less than delta
SOURCE CODE
function A = trncspmat(A,delta)
% For a sparse matrix, truncate all elements less than delta using a mask.
% There might be a better way to do this, but this way avoids having
% explicit indexing.
% Input:
%   A = sparse matrix
%   delta = cutoff threshold
% Ouput:
%   A = truncated input
    [i,j,s] = find(abs(A)>delta);
    [m,n] = size(A);
    mask = sparse(i,j,s,m,n);
    A = mask .* A;
end