Description of set
set
PURPOSE
TEMPLATE/SET Edit data stored in a Template object
SYNOPSIS
function tpl = set(tpl,action,varargin)
DESCRIPTION
TEMPLATE/SET Edit data stored in a Template object
  TPL = SET(TPL,ACTION,VARARGIN)
     ACTION 'root'
     ACTION 'unknowns'
     ACTION 'file'
     ACTION 'block'
     ACTION 'var'
CROSS-REFERENCE INFORMATION
This function calls:
get TEMPLATE/GET Access data stored in a Template object
loadtpl TEMPLATE/LOADTPL Read a template from file
set TEMPLATE/SET Edit data stored in a Template object
This function is called by:
test_pdf_2D % Test Tensor Form PDF Evolution ND
parse TEMPLATE/PARSE Fill in replacement fields with the class properties
loadtpl TEMPLATE/LOADTPL Read a template from file
set TEMPLATE/SET Edit data stored in a Template object
template TEMPLATE HTML Template Toolbox Constructor
m2html M2HTML - Documentation Generator for Matlab M-files and Toolboxes in HTML
mwizard MWIZARD - M2HTML Graphical User Interface
mwizard2 MWIZARD - M2HTML Graphical User Interface
plot2DProjectionPoint
plot2Dslice Inputs:
plot2DsliceM
plot2DslicesAroundPointGaussian Plots a visualization of the Tensor. For each pair of dimensions it
plot2DtimeMFibers Plot the time evolution of the tensor marginalized for each dimension
plot2d UNTITLED Summary of this function goes here
plot3ktensor Display a 3Way tensor
plot_tensor_by_rank
plotkTensorCell Plot a sequence of ktensors
sim_finite_run SIMULATION simulates trajectories starting from x0_list using results
sim_run SIMULATION simulates trajectories starting from x0_list using results
visres VISRES plots results from a run by MAIN_RUN.
plot2d Plot a 2d mesh using pcolor.
tensor_examples Tensor examples playground
test_VTOL
test_VTOL_tensor
test_convergence_radar % Load data
test_finite_horizon_hjb_backward_euler Test finite horizon hjb, backward euler
test_finite_horizon_hjb_euler Test finite horizon hjb, forward euler
test_finite_horizon_hjb_scaling Finite Horizon
test_infinite_horizon_hjb Test finite horizon hjb, backward euler
test_monteCarlo Monte Carlo Particle Filter
test_pdf_1D % Test Finite Difference PDF Evolution
test_pdf_1D_tensor % Test Tensor Form PDF Evolution
test_pdf_2D_PFE % Test Finite Difference PDF Evolution 2 dimensions
test_pdf_2D_tensor % Test Tensor Form PDF Evolution ND
test_pdf_ND_tensor % Test Tensor Form PDF Evolution ND
test_pdf_ND_tensor_run % Test Tensor Form PDF Evolution ND
test_run_spectral_heat Wave equation (3.13, pg 24) in Spectral Methods in MATLAB by Trefethen
SOURCE CODE
function tpl = set(tpl,action,varargin)
%TEMPLATE/SET Edit data stored in a Template object
%  TPL = SET(TPL,ACTION,VARARGIN)
%     ACTION 'root'
%     ACTION 'unknowns'
%     ACTION 'file'
%     ACTION 'block'
%     ACTION 'var'
%  Copyright (C) 2003 Guillaume Flandin <Guillaume@artefact.tk>
%  $Revision: 1.0 $Date: 2003/05/05 22:19:51 $
error(nargchk(3,5,nargin));
switch lower(action)
    case 'root'
        error(nargchk(3,3,nargin));
        if exist(varargin{1},'dir')
            tpl.root = varargin{1};
        else
            error('[Template] No such directory.');
        end
    case 'unknowns'
        error(nargchk(3,3,nargin));
        if ismember(varargin{1},{'remove' 'comment' 'keep'})
            tpl.unknowns = varargin{1};
        else
            error('[Template] Unknowns: ''remove'', ''comment'' or ''keep''.');
        end
    case 'file'
        error(nargchk(4,4,nargin));
        if iscellstr(varargin{1})
            for i=1:length(varargin{1})
                ind = find(ismember(tpl.handles,varargin{1}{i}));
                if isempty(ind)
                    tpl.handles{end+1} = varargin{1}{i};
                    if strcmp(varargin{2}{i}(1),filesep) %- absolute path (Unix)
                        tpl.file{end+1} = varargin{2}{i};
                    else %- relative path
                        tpl.file{end+1} = fullfile(tpl.root,varargin{2}{i});
                    end
                else
                    if strcmp(varargin{2}{i}(1),filesep) %- absolute path (Unix)
                        tpl.file{ind} = varargin{2}{i};
                    else %- relative path
                        tpl.file{ind} = fullfile(tpl.root,varargin{2}{i});
                    end
                end
            end
        elseif ischar(varargin{1})
            tpl = set(tpl,'file',cellstr(varargin{1}),cellstr(varargin{2}));
        else
            error('[Template] Badly formed handles.');
        end
    case 'block'
        error(nargchk(4,5,nargin));
        tpl = loadtpl(tpl,varargin{1});
        if nargin == 4
            name = varargin{2};
        else
            name = varargin{3};
        end
        str = get(tpl,'var',varargin{1});
        blk = '';
        %- look like this (keep the same number (1) of spaces between characters!)
        %  <!-- BEGIN ??? -->
        %  <!-- END ??? -->
        %%%%%%%%%%%%%%%%%%%%%%%%% WIH REGEXP %%%%%%%%%%%%%%%%%%%%%%%%
        % reg = ['<!--\s+BEGIN ' varargin{2} '\s+-->(.*)\n\s*<!--\s+END ' varargin{2} '\s+-->'];
        % [b, e] = regexp(str,reg,'once');
        % if ~isempty(b), blk = str(b:e); end %- should also remove BEGIN and END comments
        % str = regexprep(str,reg,['{' name '}']);
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %%%%%%%%%%%%%%%%%%%%%% WIHTOUT REGEXP %%%%%%%%%%%%%%%%%%%%%%%
        indbegin = findstr(str,['<!-- BEGIN ' varargin{2} ' -->']);
        indend   = findstr(str,['<!-- END ' varargin{2} ' -->']);
        if ~isempty(indbegin) & ~isempty(indend)
           blk = str(indbegin+length(['<!-- BEGIN ' varargin{2} ' -->'])+1:indend-1);
           str = [str(1:indbegin-1) '{' name '}' str(indend+length(['<!-- END ' varargin{2} ' -->'])+1:end)];
        end
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        tpl = set(tpl,'var',varargin{2},blk);
        tpl = set(tpl,'var',varargin{1},str);
    case 'var'
        error(nargchk(3,4,nargin));
        if iscellstr(varargin{1})
            for i=1:length(varargin{1})
                ind = find(ismember(tpl.varkeys,varargin{1}{i}));
                if isempty(ind)
                    tpl.varkeys{end+1} = varargin{1}{i};
                    if nargin == 4
                        tpl.varvals{end+1} = varargin{2}{i};
                    else
                        tpl.varvals{end+1} = '';
                    end
                else
                    tpl.varvals{ind} = varargin{2}{i};
                end
            end
        elseif ischar(varargin{1})
            tpl = set(tpl,'var',cellstr(varargin{1}),cellstr(varargin{2}));
        else
            error('[Template] Badly formed variable names.');
        end
    otherwise
        error('[Template] Unknown action to perform.');
end