Description of als2
als2
PURPOSE
ALS code to perform the ALS algorithm as described in Beylkin
SYNOPSIS
function [F, err, iter, e_list, t_step, illcond, noreduce] = als2(op,varargin)
DESCRIPTION
 ALS code to perform the ALS algorithm as described in Beylkin
 and Mohlenkamp 2005.
 Input:
   op - tensor to be approximated.
   optional - optional inputs:
      e - desired accuracy.
      maxit - maximum number of iterations.
      Pinit - inital guess (cell array).
      if options is empty, ALS will use the default setup maxit = 2000, e
      = 1e-3 and Pinit = random tensor.
 Output:
   F - the low rank approimxation of G.
   err - the error during the run.
   iter - the number of iterations.
   Fcond - the condition number of F during the run.
   e_list - index when tensor term is added.
   t_step - computing time for als onestep during the run.
   illcond - 1 if a als matrice were illcond, otherwise 0.
   noreduce - 1 if als couldn't reduce rank, otherwise 0.
 See also MAIN_RUN.
CROSS-REFERENCE INFORMATION
This function calls:
cp_als CP_ALS Compute a CP decomposition of any type of tensor.
cp_nmu CP_NMU Compute nonnegative CP with multiplicative updates.
This function is called by:
test_pdf_2D % Test Tensor Form PDF Evolution ND
create_FP_op
diffop_region REGIONDIFFOP Adds boundary conditions to derivative for the region.
diffop_region_spectral REGIONDIFFOP Adds boundary conditions to derivative for the region.
main_run MAIN_RUN obtains the solution to the setup specified in MAIN_PROGRAM,
main_run_spectral MAIN_RUN obtains the solution to the setup specified in MAIN_PROGRAM,
tensor_examples Tensor examples playground
test_VTOL_tensor
test_convergence_radar % Load data
test_finite_horizon_hjb_backward_euler Test finite horizon hjb, backward euler
test_finite_horizon_hjb_euler Test finite horizon hjb, forward euler
test_finite_horizon_hjb_scaling Finite Horizon
test_infinite_horizon_hjb Test finite horizon hjb, backward euler
test_pdf_1D_tensor % Test Tensor Form PDF Evolution
test_pdf_2D_tensor % Test Tensor Form PDF Evolution ND
test_pdf_ND_tensor % Test Tensor Form PDF Evolution ND
test_pdf_ND_tensor_run % Test Tensor Form PDF Evolution ND
test_run_spectral_heat Wave equation (3.13, pg 24) in Spectral Methods in MATLAB by Trefethen
test_run_spectral_helmholtz Helmholtz equation (7.6) in Spectral Methods in MATLAB by Trefethen
test_run_spectral_periodic Poisson equation (pg 119) in Spectral Methods in MATLAB by Trefethen
SOURCE CODE
function [F, err, iter, e_list, t_step, illcond, noreduce] = als2(op,varargin)
% ALS code to perform the ALS algorithm as described in Beylkin
% and Mohlenkamp 2005.
% Input:
%   op - tensor to be approximated.
%   optional - optional inputs:
%      e - desired accuracy.
%      maxit - maximum number of iterations.
%      Pinit - inital guess (cell array).
%      if options is empty, ALS will use the default setup maxit = 2000, e
%      = 1e-3 and Pinit = random tensor.
% Output:
%   F - the low rank approimxation of G.
%   err - the error during the run.
%   iter - the number of iterations.
%   Fcond - the condition number of F during the run.
%   e_list - index when tensor term is added.
%   t_step - computing time for als onestep during the run.
%   illcond - 1 if a als matrice were illcond, otherwise 0.
%   noreduce - 1 if als couldn't reduce rank, otherwise 0.
%
% See also MAIN_RUN.
dim = ndims(op);
R = ncomponents(op);
op_len = length(varargin);
illcond = 0;
if op_len < 5
    fullBasis = 1;
else
    fullBasis = varargin{5};
end
if op_len < 4
    curr_rank = 1;
else
    curr_rank = varargin{4};
end
if op_len < 3
    Pinit = cell(1,dim);
    for ii = 1:dim
        Pinit{ii} = matrandnorm(size(op.U{ii},1),1);
    end
else
    Pinit = varargin{3};
    if isempty(Pinit)
        Pinit = cell(1,dim);
        for ii = 1:dim
            Pinit{ii} = matrandnorm(size(op.U{ii},1),1);
        end
    end
end
if op_len < 2
    maxit = 2000;
else
    maxit = varargin{2};
end
if op_len < 1
     e = 1e-4;
else
    e = abs(varargin{1});
end
%curr_rank = 1;
iter = 0;
err = zeros(maxit,1);
t_step = zeros(maxit,1);
tol = 1000;
noreduce = 0;
e_list = 1;
while (iter < maxit) && (tol > e) && (curr_rank < R) && ~(illcond)
    if (fullBasis)
        [P,~,out]= cp_als(op,curr_rank,'init',Pinit,'printitn',0);
    else
        curr_rank = min(curr_rank,4);
        [P,~,out]= cp_nmu(op,curr_rank);
    end
    iter = iter + out.iters;
    e_list = [e_list out.iters+1];
    tol = out.err(out.iters);
    illcond = out.ill_cond;
    err(iter-out.iters+1:iter) = out.err;
    t_step(iter-out.iters+1:iter) = out.t_step;
    for ii = 1:dim
        Pinit{ii} = [P.U{ii} matrandnorm(size(P.U{ii},1),1)];
    end
    curr_rank = curr_rank + 1;
end
t_step = t_step(1:iter);
err = err(1:iter);
if curr_rank == R
    F = op;
    if iter == 0
        err = 0;
    else
        err(iter) = 0;
    end
    disp('cannot reduce rank')
    noreduce = 1;
else
    F = P;
end
if (iter == maxit && err(iter) > e)
    disp('Max iterations reached without finding a good solution')
end