Description of blockTransposeH2V
blockTransposeH2V
PURPOSE
SYNOPSIS
function [At] = blockTransposeH2V(A, blksize)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
SRMultM SRMULTM multiplies two ktensor operators A and B. The result is a new
SRMultV SRMULTV multiplies a ktensor operators A with a ktensor function F. The
als_test_code load('./test/test_data_smooth2D.mat')
SOURCE CODE
function [At] = blockTransposeH2V(A, blksize)
sizeA = size(A);
At = reshape(permute(reshape(A, sizeA(1), blksize, []), [2 1 3]), blksize,[])';