Description of cp_als
cp_als
PURPOSE
CP_ALS Compute a CP decomposition of any type of tensor.
SYNOPSIS
function [P,Uinit,output] = cp_als(X,R,varargin)
DESCRIPTION
CP_ALS Compute a CP decomposition of any type of tensor.
   P = CP_ALS(X,R) computes an estimate of the best rank-R
   CP model of a tensor X using an alternating least-squares
   algorithm.  The input X can be a tensor, sptensor, ktensor, or
   ttensor. The result P is a ktensor.
   P = CP_ALS(X,R,'param',value,...) specifies optional parameters and
   values. Valid parameters and their default values are:
      'tol' - Tolerance on difference in fit {1.0e-4}
      'maxiters' - Maximum number of iterations {50}
      'dimorder' - Order to loop through dimensions {1:ndims(A)}
      'init' - Initial guess [{'random'}|'nvecs'|cell array]
      'printitn' - Print fit every n iterations; 0 for no printing {1}
   [P,U0] = CP_ALS(...) also returns the initial guess.
   [P,U0,out] = CP_ALS(...) also returns additional output that contains
   the input parameters.
   Note: The "fit" is defined as 1 - norm(X-full(P))/norm(X) and is
   loosely the proportion of the data described by the CP model, i.e., a
   fit of 1 is perfect.
   NOTE: Updated in various minor ways per work of Phan Anh Huy. See Anh
   Huy Phan, Petr Tichavský, Andrzej Cichocki, On Fast Computation of
   Gradients for CANDECOMP/PARAFAC Algorithms, arXiv:1204.1586, 2012.
   Examples:
   X = sptenrand([5 4 3], 10);
   P = cp_als(X,2);
   P = cp_als(X,2,'dimorder',[3 2 1]);
   P = cp_als(X,2,'dimorder',[3 2 1],'init','nvecs');
   U0 = {rand(5,2),rand(4,2),[]}; %<-- Initial guess for factors of P
   [P,U0,out] = cp_als(X,2,'dimorder',[3 2 1],'init',U0);
   P = cp_als(X,2,out.params); %<-- Same params as previous run
   See also KTENSOR, TENSOR, SPTENSOR, TTENSOR.
MATLAB Tensor Toolbox.
Copyright 2015, Sandia Corporation.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
test_pdf_2D % Test Tensor Form PDF Evolution ND
als2 ALS code to perform the ALS algorithm as described in Beylkin
tensor_examples Tensor examples playground
test_convergence_radar % Load data
test_finite_horizon_hjb_backward_euler Test finite horizon hjb, backward euler
test_finite_horizon_hjb_scaling Finite Horizon
test_pdf_2D_tensor % Test Tensor Form PDF Evolution ND
test_pdf_ND_tensor % Test Tensor Form PDF Evolution ND
SOURCE CODE
function [P,Uinit,output] = cp_als(X,R,varargin)
%CP_ALS Compute a CP decomposition of any type of tensor.
%
%   P = CP_ALS(X,R) computes an estimate of the best rank-R
%   CP model of a tensor X using an alternating least-squares
%   algorithm.  The input X can be a tensor, sptensor, ktensor, or
%   ttensor. The result P is a ktensor.
%
%   P = CP_ALS(X,R,'param',value,...) specifies optional parameters and
%   values. Valid parameters and their default values are:
%      'tol' - Tolerance on difference in fit {1.0e-4}
%      'maxiters' - Maximum number of iterations {50}
%      'dimorder' - Order to loop through dimensions {1:ndims(A)}
%      'init' - Initial guess [{'random'}|'nvecs'|cell array]
%      'printitn' - Print fit every n iterations; 0 for no printing {1}
%
%   [P,U0] = CP_ALS(...) also returns the initial guess.
%
%   [P,U0,out] = CP_ALS(...) also returns additional output that contains
%   the input parameters.
%
%   Note: The "fit" is defined as 1 - norm(X-full(P))/norm(X) and is
%   loosely the proportion of the data described by the CP model, i.e., a
%   fit of 1 is perfect.
%
%   NOTE: Updated in various minor ways per work of Phan Anh Huy. See Anh
%   Huy Phan, Petr Tichavský, Andrzej Cichocki, On Fast Computation of
%   Gradients for CANDECOMP/PARAFAC Algorithms, arXiv:1204.1586, 2012.
%
%   Examples:
%   X = sptenrand([5 4 3], 10);
%   P = cp_als(X,2);
%   P = cp_als(X,2,'dimorder',[3 2 1]);
%   P = cp_als(X,2,'dimorder',[3 2 1],'init','nvecs');
%   U0 = {rand(5,2),rand(4,2),[]}; %<-- Initial guess for factors of P
%   [P,U0,out] = cp_als(X,2,'dimorder',[3 2 1],'init',U0);
%   P = cp_als(X,2,out.params); %<-- Same params as previous run
%
%   See also KTENSOR, TENSOR, SPTENSOR, TTENSOR.
%
%MATLAB Tensor Toolbox.
%Copyright 2015, Sandia Corporation.
% This is the MATLAB Tensor Toolbox by T. Kolda, B. Bader, and others.
% http://www.sandia.gov/~tgkolda/TensorToolbox.
% Copyright (2015) Sandia Corporation. Under the terms of Contract
% DE-AC04-94AL85000, there is a non-exclusive license for use of this
% work by or on behalf of the U.S. Government. Export of this data may
% require a license from the United States Government.
% The full license terms can be found in the file LICENSE.txt
warning('error', 'MATLAB:nearlySingularMatrix');
%% Extract number of dimensions and norm of X.
N = ndims(X);
normX = norm(X);
%% Set algorithm parameters from input or by using defaults
params = inputParser;
params.addParamValue('tol',1e-4,@isscalar);
params.addParamValue('maxiters',50,@(x) isscalar(x) & x > 0);
params.addParamValue('dimorder',1:N,@(x) isequal(sort(x),1:N));
params.addParamValue('init', 'random', @(x) (iscell(x) || ismember(x,{'random','nvecs'})));
params.addParamValue('printitn',1,@isscalar);
params.parse(varargin{:});
%% Copy from params object
fitchangetol = params.Results.tol;
maxiters = params.Results.maxiters;
dimorder = params.Results.dimorder;
init = params.Results.init;
printitn = params.Results.printitn;
%% Error checking
%% Set up and error checking on initial guess for U.
if iscell(init)
    Uinit = init;
    if numel(Uinit) ~= N
        error('OPTS.init does not have %d cells',N);
    end
    for n = dimorder(2:end);
        if ~isequal(size(Uinit{n}),[size(X,n) R])
            error('OPTS.init{%d} is the wrong size',n);
        end
    end
else
    % Observe that we don't need to calculate an initial guess for the
    % first index in dimorder because that will be solved for in the first
    % inner iteration.
    if strcmp(init,'random')
        Uinit = cell(N,1);
        for n = dimorder(2:end)
            Uinit{n} = rand(size(X,n),R);
        end
    elseif strcmp(init,'nvecs') || strcmp(init,'eigs')
        Uinit = cell(N,1);
        for n = dimorder(2:end)
            Uinit{n} = nvecs(X,n,R);
        end
    else
        error('The selected initialization method is not supported');
    end
end
%% Set up for iterations - initializing U and the fit.
U = Uinit;
fit = 0;
ill_cond = 0;
if printitn>0
  fprintf('\nCP_ALS:\n');
end
%% Main Loop: Iterate until convergence
if (isa(X,'sptensor') || isa(X,'tensor')) && (exist('cpals_core','file') == 3)
    %fprintf('Using C++ code\n');
    [lambda,U] = cpals_core(X, Uinit, fitchangetol, maxiters, dimorder);
    P = ktensor(lambda,U);
else
    UtU = zeros(R,R,N);
    for n = 1:N
        if ~isempty(U{n})
            UtU(:,:,n) = U{n}'*U{n};
        end
    end
    err = zeros(maxiters,1);
    t_step = zeros(maxiters,1);
    for iter = 1:maxiters
        tic
        fitold = fit;
        % Iterate over all N modes of the tensor
        for n = dimorder(1:end)
            % Calculate Unew = X_(n) * khatrirao(all U except n, 'r').
            Unew = mttkrp(X,U,n);
            % Compute the matrix of coefficients for linear system
            Y = prod(UtU(:,:,[1:n-1 n+1:N]),3);
            try
                Unew = Unew / Y;
            catch
                ill_cond = 1;
                warning('off', 'MATLAB:nearlySingularMatrix');
                Unew = Unew / Y;
                warning('error', 'MATLAB:nearlySingularMatrix');
            end
            if issparse(Unew)
                Unew = full(Unew);   % for the case R=1
            end
            if cond(Y) > 1e13
                ill_cond = 1;
            end
            % Normalize each vector to prevent singularities in coefmatrix
            if iter == 1
                lambda = sqrt(sum(Unew.^2,1))'; %2-norm
            else
                lambda = max( max(abs(Unew),[],1), 1 )'; %max-norm
            end
            try
                Unew = bsxfun(@rdivide, Unew, lambda');
            catch
                ill_cond = 1;
                warning('off', 'MATLAB:nearlySingularMatrix');
                Unew = bsxfun(@rdivide, Unew, lambda');
                warning('error', 'MATLAB:nearlySingularMatrix');
            end
            U{n} = Unew;
            UtU(:,:,n) = U{n}'*U{n};
        end
        P = ktensor(lambda,U);
        if normX == 0
            fit = norm(P)^2 - 2 * innerprod(X,P);
            err(iter) = 1-fit;
        else
            try
                normresidual = norm(X-P); %sqrt( normX^2 + norm(P)^2 - 2 * innerprod(X,P) );
            catch
                normresidual = sqrt( normX^2 + norm(P)^2 - 2 * innerprod(X,P) );
            end
            err(iter) = normresidual/normX;
            fit = 1 - err(iter); %fraction explained by model
        end
        fitchange = abs(fitold - fit);
        % Check for convergence
        if (iter > 1) && (fitchange < fitchangetol)
            flag = 0;
        else
            flag = 1;
        end
        if (mod(iter,printitn)==0) || ((printitn>0) && (flag==0))
            fprintf(' Iter %2d: f = %e f-delta = %7.1e\n', iter, fit, fitchange);
        end
        % Check for convergence
        if (flag == 0)
            break;
        end
        t_step(iter) = toc;
        if ill_cond
            fprintf('Matrix is ill condition. \n')
            break
        end
    end
end
%% Clean up final result
% Arrange the final tensor so that the columns are normalized.
P = arrange(P);
% Fix the signs
P = fixsigns(P);
if printitn>0
    if normX == 0
        fit = norm(P)^2 - 2 * innerprod(X,P);
    else
        try
            normresidual = norm(X-P); %sqrt( normX^2 + norm(P)^2 - 2 * innerprod(X,P) );
        catch
            normresidual = sqrt( normX^2 + norm(P)^2 - 2 * innerprod(X,P) );
        end
        fit = 1 - (normresidual / normX); %fraction explained by model
    end
  fprintf(' Final f = %e, error = %e\n', fit, 1-fit);
end
output = struct;
output.params = params.Results;
output.iters = iter;
output.err = err(1:iter);
output.ill_cond = ill_cond;
output.t_step = t_step(1:iter);
warning('on', 'MATLAB:nearlySingularMatrix');