Description of DiagKTensor
DiagKTensor
PURPOSE
DIAGKTENSOR Diagonalize a series of vectors in each dimension to a
SYNOPSIS
function [tens] = DiagKTensor(vec)
DESCRIPTION
 DIAGKTENSOR Diagonalize a series of vectors in each dimension to a
 diagonal tensor operator
Input:
   vec - ktensor
Output:
   tens - corresponding ktensor operator
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
test_pdf_2D % Test Tensor Form PDF Evolution ND
DiagMatKTensor MATKTENS converts a cell array of ktensor functions to corresponding cell
artdiff_ver2 ARTDIFF_VER1 is the second version for adding artificial diffusion.
artdiff_ver3 ARTDIFF_VER1 is the third version for adding artificial diffusion.
create_FP_op
makeop MAKEOP creates the operator of the linear HJB equation.
test_finite_horizon_hjb_backward_euler Test finite horizon hjb, backward euler
test_finite_horizon_hjb_euler Test finite horizon hjb, forward euler
test_finite_horizon_hjb_scaling Finite Horizon
test_pdf_1D_tensor % Test Tensor Form PDF Evolution
test_pdf_2D_tensor % Test Tensor Form PDF Evolution ND
test_pdf_ND_tensor % Test Tensor Form PDF Evolution ND
test_run_spectral_heat Wave equation (3.13, pg 24) in Spectral Methods in MATLAB by Trefethen
test_run_spectral_helmholtz Helmholtz equation (7.6) in Spectral Methods in MATLAB by Trefethen
test_run_spectral_periodic Poisson equation (pg 119) in Spectral Methods in MATLAB by Trefethen
SOURCE CODE
function [tens] = DiagKTensor(vec)
% DIAGKTENSOR Diagonalize a series of vectors in each dimension to a
% diagonal tensor operator
%Input:
%   vec - ktensor
%Output:
%   tens - corresponding ktensor operator
d = ndims(vec);
sr = ncomponents(vec);
% incooporate scale factors into vec, evenly distributed. Then we
% don't need to worry about vec.lambda
for i=1:d
    vec.U{i} = vec.U{i}*diag((vec.lambda.^(1/d)));
end
vec.lambda = ones(sr,1);
Ut = cell(1,d);
for i=1:d
    myDiag = diag(vec.U{i}(:,1));
    Ut{i} = myDiag(:);
end
tens = ktensor(Ut);
for k=2:sr
    Ut = cell(1,d);
    for i=1:d
        myDiag = diag(vec.U{i}(:,k));
        Ut{i} = myDiag(:);
    end
    tens = tens + ktensor(Ut);
end
end