Description of EvalTMat
EvalTMat
PURPOSE
EVALTMAT evaluates a matrix-valued ktensor function at a point x
SYNOPSIS
function [ y ] = EvalTMat(TMat, x, gridT)
DESCRIPTION
 EVALTMAT evaluates a matrix-valued ktensor function at a point x
 Inputs:
   TMat - the matrix-valued ktensor function.
   x - the points where the value of TMat should be evaluated.
   grid - the discretization grid.
 Outputs:
   y - the value at x (a matrix).
CROSS-REFERENCE INFORMATION
This function calls:
EvalT EVALT evaluates a ktensor (function) at an individual point
This function is called by:
sim_finite_run SIMULATION simulates trajectories starting from x0_list using results
sim_run SIMULATION simulates trajectories starting from x0_list using results
SOURCE CODE
function [ y ] = EvalTMat(TMat, x, gridT)
% EVALTMAT evaluates a matrix-valued ktensor function at a point x
% Inputs:
%   TMat - the matrix-valued ktensor function.
%   x - the points where the value of TMat should be evaluated.
%   grid - the discretization grid.
% Outputs:
%   y - the value at x (a matrix).
[n,m] = size(TMat);
y = zeros(n,m);
for i=1:n
    for j=1:m
        y(i,j) = EvalT(TMat{i,j},x,gridT);
    end
end
end