Description of EvalT
EvalT
PURPOSE
EVALT evaluates a ktensor (function) at an individual point
SYNOPSIS
function [y] = EvalT(tens,x,grid)
DESCRIPTION
 EVALT evaluates a ktensor (function) at an individual point
 Inputs:
   tens - the ktensor.
   x - the point where the ktensor value should be evaluated.
   grid - the discretization grid.
 Outputs:
   y - the value at x.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
EvalTMat EVALTMAT evaluates a matrix-valued ktensor function at a point x
sim_finite_run SIMULATION simulates trajectories starting from x0_list using results
sim_run SIMULATION simulates trajectories starting from x0_list using results
test_finite_horizon_hjb_backward_euler Test finite horizon hjb, backward euler
test_finite_horizon_hjb_scaling Finite Horizon
test_infinite_horizon_hjb Test finite horizon hjb, backward euler
SOURCE CODE
function [y] = EvalT(tens,x,grid)
% EVALT evaluates a ktensor (function) at an individual point
% Inputs:
%   tens - the ktensor.
%   x - the point where the ktensor value should be evaluated.
%   grid - the discretization grid.
% Outputs:
%   y - the value at x.
y = tens.lambda';
for i=1:length(x);
    y = y.*interp1( grid{i}, tens.U{i}, x(i) );
end
y = sum(y);
end