Description of fitTensorBoundaries
fitTensorBoundaries
PURPOSE
SYNOPSIS
function [ tensorOutput, gridTnew, dx ] = fitTensorBoundaries(tens, gridT, meanT, covT, ngridT, lambda)
DESCRIPTION
  Adjust the boundaries of the pdf to lambda sigmas around the mean
       Input:
  tens,
  gridT,
  meanT,
  covT,
  ngridT,
  lambda
       Output:
  tensorOutput,
  gridTnew
CROSS-REFERENCE INFORMATION
This function calls:
interpTensor
This function is called by:
tensor_examples Tensor examples playground
test_VTOL_tensor
test_pdf_ND_tensor_run % Test Tensor Form PDF Evolution ND
SOURCE CODE
function [ tensorOutput, gridTnew, dx ] = fitTensorBoundaries(tens, gridT, meanT, covT, ngridT, lambda)
%
%  Adjust the boundaries of the pdf to lambda sigmas around the mean
%
%       Input:
%  tens,
%  gridT,
%  meanT,
%  covT,
%  ngridT,
%  lambda
%       Output:
%  tensorOutput,
%  gridTnew
    % Check input
    validateattributes(tens,{'ktensor'},{'nonempty'})
    dim = ndims(tens);
    validateattributes(gridT,{'cell'},{'numel',dim})
    validateattributes(meanT,{'double'},{'numel',dim})
    validateattributes(ngridT,{'double'},{'numel',dim})
    validateattributes(covT,{'double'},{'size',[dim,dim]})
    validateattributes(lambda,{'double'},{'numel',1})
    gridTnew = cell(dim,1);
    bdim = zeros(dim,2);
    dx = zeros(dim,1);
    for i=1:dim
        bdim(i,:) = [meanT(i)-lambda*sqrt(covT(i,i)) meanT(i)+lambda*sqrt(covT(i,i))];
        dx(i) = (bdim(i,2)-bdim(i,1))/(ngridT(i)-1);
        gridTnew{i} =  (bdim(i,1):dx(i):bdim(i,2))';
    end
    tensorOutput = interpTensor(tens,gridT,gridTnew);
end