Description of HadTensProd
HadTensProd
PURPOSE
HadTensProd performs Hadamand tensor products for a ktensor function F
SYNOPSIS
function res = HadTensProd(F,G)
DESCRIPTION
 HadTensProd performs Hadamand tensor products for a ktensor function F
 and a ktensor function G. The result is a new ktensor function FG.
 Input:
   F - ktensor function.
   G - ktensor function.
 Output:
   FG - the Hadamand product of F and G.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
test_pdf_2D % Test Tensor Form PDF Evolution ND
test_VTOL_tensor
test_pdf_1D_tensor % Test Tensor Form PDF Evolution
test_pdf_2D_tensor % Test Tensor Form PDF Evolution ND
test_pdf_ND_tensor % Test Tensor Form PDF Evolution ND
test_pdf_ND_tensor_run % Test Tensor Form PDF Evolution ND
SOURCE CODE
function res = HadTensProd(F,G)
% HadTensProd performs Hadamand tensor products for a ktensor function F
% and a ktensor function G. The result is a new ktensor function FG.
% Input:
%   F - ktensor function.
%   G - ktensor function.
% Output:
%   FG - the Hadamand product of F and G.
nd = ndims(F);
if nd ~= ndims(G)
    error('The dimensions of the ktensors must be the same')
end
if size(F) ~= size(G)
    error('The sizes of the ktensors must be the same')
end
rF = ncomponents(F);
rG = ncomponents(G);
LL = G.lambda*F.lambda';
FG = cell(nd,1);
for nn = 1:nd
    N = size(F,nn);
    F_U = F.U{nn};
    temp = zeros(N,rF*rG);
    for ii = 1:rF
        temp(:,((ii-1)*rG)+(1:rG)) = bsxfun(@times, G.U{nn}, F_U(:,ii));
    end
    FG{nn} = temp;
end
res = ktensor(LL(:),FG);
res = fixsigns(arrange(res));