Description of incorpregion
incorpregion
PURPOSE
INCORPREGION modifies operator and boundary conditions to incooporate
SYNOPSIS
function [op,bc] = incorpregion(op,bc,region,grid,regval,regsca)
DESCRIPTION
 INCORPREGION modifies operator and boundary conditions to incooporate
 Dirichlet boundary conditions at the goal region.
 Inputs:
   op - the operator as ktensor
   bc - the boundary conditions as ktensor.
   region - the dimensions of the goal region.
   grid - the discretization grid.
   regval - the Dirichlet value at the goal region.
   regsca - the boundary scaling at the goal region.
 Outputs:
   op - the adjusted operator.
   bc - the adjusted boundary conditions.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
main_run MAIN_RUN obtains the solution to the setup specified in MAIN_PROGRAM,
main_run_spectral MAIN_RUN obtains the solution to the setup specified in MAIN_PROGRAM,
make_bc_sca MAKE_BC_SCA creates scalings for the boundary condition and goal region
SOURCE CODE
function [op,bc] = incorpregion(op,bc,region,grid,regval,regsca)
% INCORPREGION modifies operator and boundary conditions to incooporate
% Dirichlet boundary conditions at the goal region.
% Inputs:
%   op - the operator as ktensor
%   bc - the boundary conditions as ktensor.
%   region - the dimensions of the goal region.
%   grid - the discretization grid.
%   regval - the Dirichlet value at the goal region.
%   regsca - the boundary scaling at the goal region.
% Outputs:
%   op - the adjusted operator.
%   bc - the adjusted boundary conditions.
% Elis Stefansson, Aug 2015
sr = ncomponents(op);
sr_b = ncomponents(bc);
d = length(grid);
% select out the region from the operator
opAdd = cell(1,d);
opRem = op;
bcAdd = cell(d,1); %will be the added bc in region.
bcd = bc; %will be a copy of bc in region
for i=1:d
    gridi = grid{i};
    ni = length(gridi);
    d_ind = (gridi >= region(i,1)) & (gridi <= region(i,2));
    d_out = (gridi < region(i,1)) | (gridi > region(i,2));
    %Go through each rank and eliminate nodes outside region
    temp = reshape(opRem.U{i},ni,ni*sr);
    temp(d_out,:) = 0;
    opRem.U{i} = reshape(temp,ni*ni,sr);
    %Create identity for nodes inside region
    id = eye(ni);
    id(d_out,:) = 0;
    id(:,d_out) = 0;
    opAdd{i} = id(:);
    %Go through the boundary and eliminate nodes outside region
    newBCU = bcd.U{i};
    newBCU(d_out,:) = zeros(sum(d_out),sr_b);
    bcd.U{i} = newBCU;
    bcAdd{i} = zeros(ni,1);
    bcAdd{i}(d_ind,1) = ones(sum(d_ind),1);
end
op = fixsigns(arrange(op - opRem + regsca*ktensor(opAdd)));
bc = fixsigns(arrange(bc - bcd + regsca*regval*ktensor(bcAdd)));
end