Description of intTens
intTens
PURPOSE
F - ktensor
SYNOPSIS
function [Fint] = intTens(F, dim, gridT, w)
DESCRIPTION
 F - ktensor
 grid - grid in each dimension in cell
 w - integration weight in each dimension in cell
 dim - dimensions to integrate over
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
test_pdf_2D % Test Tensor Form PDF Evolution ND
meanCovTensor Compute the mean and covariance of a tensor
plot2DsliceM
plot2DtimeMFibers Plot the time evolution of the tensor marginalized for each dimension
tensor_examples Tensor examples playground
test_VTOL_tensor
test_convergence_radar % Load data
test_intTens
test_pdf_2D_tensor % Test Tensor Form PDF Evolution ND
test_pdf_ND_tensor % Test Tensor Form PDF Evolution ND
test_pdf_ND_tensor_run % Test Tensor Form PDF Evolution ND
SOURCE CODE
function [Fint] = intTens(F, dim, gridT, w)
% F - ktensor
% grid - grid in each dimension in cell
% w - integration weight in each dimension in cell
% dim - dimensions to integrate over
nd = ndims(F);
if nargin < 4 || isempty(w)
    for ii = 1:nd
        w{ii} = ones(size(F.U{ii},1),1);
    end
end
if nargin < 3 || isempty(gridT)
    for ii = 1:nd
        gridT{ii} = (1:size(F.U{ii},1))';
    end
end
if nargin < 2 || isempty(dim)
    dim = 1:nd;
end
if length(dim) ~= nd
    Fintc = cell(1, nd - length(dim));
else
    Fintc = cell(1, 1);
end
Fint_lambda = F.lambda';
int_all = 0;
for ii = 1:nd
    if any(ii == dim)
        Fintc{ii} = trapz(gridT{ii},bsxfun(@times,F.U{ii},w{ii}));%w{ii}'*F.U{ii};
        Fint_lambda = Fint_lambda.*Fintc{ii};
    else
        Fintc{ii} = F.U{ii};
    end
    int_all = int_all + size(Fintc{ii},1);
end
if int_all == nd
    Fint = sum(Fint_lambda);
else
    Fint = ktensor(F.lambda, Fintc);
end