Description of meanCovTensor
meanCovTensor
PURPOSE
Compute the mean and covariance of a tensor
SYNOPSIS
function [ meanT, covT ] = meanCovTensor(itens, gridT, weMean, weCov, weOnes)
DESCRIPTION
 Compute the mean and covariance of a tensor
 itens,
 gridT, cell(n,1)
 weMean, weights for the mean. cell(dim,dim);
 weCov, weights for the covariance, cell(dim,dim,dim);
CROSS-REFERENCE INFORMATION
This function calls:
intTens F - ktensor
This function is called by:
plot2DtimeMFibers Plot the time evolution of the tensor marginalized for each dimension
plotkTensor Plot a ktensor using different plotting styles
tensor_examples Tensor examples playground
test_VTOL_tensor
test_pdf_ND_tensor_run % Test Tensor Form PDF Evolution ND
SOURCE CODE
function [ meanT, covT ] = meanCovTensor(itens, gridT, weMean, weCov, weOnes)
% Compute the mean and covariance of a tensor
%
% itens,
% gridT, cell(n,1)
% weMean, weights for the mean. cell(dim,dim);
% weCov, weights for the covariance, cell(dim,dim,dim);
    dim = ndims(itens);
    itens = itens*(1/intTens(itens, [], gridT, weOnes)); %normalice
    meanT = zeros(dim,1);
    for i=1:dim
        meanT(i)  = intTens(itens, [], gridT, weMean(i,:));
    end
    covT = zeros(dim,dim);
    for i=1:dim
        for j = 1:dim
            covT(i,j) = intTens(itens, [], gridT, weCov(i,j,:)) - meanT(i)*meanT(j);
        end
    end
end