Description of oneTens
oneTens
PURPOSE
Create a d dimensional all ones tensor of size n
SYNOPSIS
function idTens = oneTens(d, n)
DESCRIPTION
 Create a d dimensional all ones tensor of size n
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
makebcforward MAKEBC modifies the ktensor to incooporate boundary conditions.
test_finite_horizon_hjb_backward_euler Test finite horizon hjb, backward euler
test_finite_horizon_hjb_euler Test finite horizon hjb, forward euler
test_finite_horizon_hjb_scaling Finite Horizon
SOURCE CODE
function idTens = oneTens(d, n)
% Create a d dimensional all ones tensor of size n
% Inputs:
% d - number of dimensions
% n - length of each dimension
% Output:
% idTens - ktensor of all ones
if length(n) == 1
    n = n*ones(1,d);
elseif length(n) ~= d
    error('length(n) must be the same as the dimension')
end
U = cell(d,1);
for i = 1:d
    U{i} = ones(n(i),1);
end
idTens = ktensor(U);
end