Description of plot2d
plot2d
PURPOSE
UNTITLED Summary of this function goes here
SYNOPSIS
function [ ] = plot2d(xvector,zmatrix)
DESCRIPTION
UNTITLED Summary of this function goes here
   Detailed explanation goes here
CROSS-REFERENCE INFORMATION
This function calls:
set TEMPLATE/SET Edit data stored in a Template object
This function is called by:
test_pdf_2D % Test Tensor Form PDF Evolution ND
test_pdf_2D_PFE % Test Finite Difference PDF Evolution 2 dimensions
test_pdf_2D_tensor % Test Tensor Form PDF Evolution ND
test_pdf_ND_tensor % Test Tensor Form PDF Evolution ND
SOURCE CODE
function [  ] = plot2d(xvector,zmatrix)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
    hh = pcolor(xvector{1}',xvector{2}',zmatrix');
    colorbar
    set(hh, 'EdgeColor', 'none');
    xlabel('x')
    zlabel('p(x)')
    grid on
end