Description of SRMultM
SRMultM
PURPOSE
SRMULTM multiplies two ktensor operators A and B. The result is a new
SYNOPSIS
function res = SRMultM(A,B)
DESCRIPTION
 SRMULTM multiplies two ktensor operators A and B. The result is a new
 ktensor AB.
 Input:
   A - ktensor operator A.
   B - ktensor operator B.
 Output:
   AB - the product of A and B.
 Note:
 The matrices of A and B are stored as vectors. For
 example, a matrix of size mxm is stored as a vector with m^2 entries.
 SRMULTM is for example used in HESSIAN.
CROSS-REFERENCE INFORMATION
This function calls:
blockTransposeH2V
blockTransposeV2H
This function is called by:
TMatM TMATM Tensor Matrix Multiply. Multiplies two cell array with ktensor
artdiff_ver2 ARTDIFF_VER1 is the second version for adding artificial diffusion.
artdiff_ver3 ARTDIFF_VER1 is the third version for adding artificial diffusion.
create_FP_op
hessian HESSIAN generates the Hessian operator as a cell array with ktensor
makeop MAKEOP creates the operator of the linear HJB equation.
als_test_code load('./test/test_data_smooth2D.mat')
test_pdf_1D_tensor % Test Tensor Form PDF Evolution
test_run_spectral_heat Wave equation (3.13, pg 24) in Spectral Methods in MATLAB by Trefethen
test_run_spectral_periodic Poisson equation (pg 119) in Spectral Methods in MATLAB by Trefethen
SOURCE CODE
function res = SRMultM(A,B)
% SRMULTM multiplies two ktensor operators A and B. The result is a new
% ktensor AB.
% Input:
%   A - ktensor operator A.
%   B - ktensor operator B.
% Output:
%   AB - the product of A and B.
%
% Note:
% The matrices of A and B are stored as vectors. For
% example, a matrix of size mxm is stored as a vector with m^2 entries.
%
% SRMULTM is for example used in HESSIAN.
rA = ncomponents(A);
rB = ncomponents(B);
nd = ndims(A);
LL = B.lambda*A.lambda';
AB = cell(nd,1);
for nn = 1:nd
    N = round(sqrt(size(B,nn)));
    AB{nn} = reshape(blockTransposeV2H(blockTransposeH2V(reshape(A.U{nn},N,N*rA),N)*reshape(B.U{nn},N,N*rB),N),N*N,[]);
end
res = ktensor(LL(:),AB);
res = fixsigns(arrange(res));