Description of SRMultV
SRMultV
PURPOSE
SRMULTV multiplies a ktensor operators A with a ktensor function F. The
SYNOPSIS
function res = SRMultV(A,F)
DESCRIPTION
 SRMULTV multiplies a ktensor operators A with a ktensor function F. The
 result is a new ktensor function AF.
 Input:
   A - ktensor operator.
   F - ktensor function.
 Output:
   AB - the product of A and B.
 Note:
 The ktensor operator A stores it corresponding matrices as vectors. For
 example, a matrix of size mxm is stored as a vector with m^2 entries.
CROSS-REFERENCE INFORMATION
This function calls:
blockTransposeH2V
blockTransposeV2H
This function is called by:
test_pdf_2D % Test Tensor Form PDF Evolution ND
als_sys ALS_SYS code to perform the ALS algorithm as described in Beylkin
als_sys_var ALS_SYS_VAR is a modified version of the original ALS algorithm found
artdiff_ver2 ARTDIFF_VER1 is the second version for adding artificial diffusion.
artdiff_ver3 ARTDIFF_VER1 is the third version for adding artificial diffusion.
sim_finite_run SIMULATION simulates trajectories starting from x0_list using results
sim_run SIMULATION simulates trajectories starting from x0_list using results
als_test_code load('./test/test_data_smooth2D.mat')
test_VTOL_tensor
test_finite_horizon_hjb_backward_euler Test finite horizon hjb, backward euler
test_finite_horizon_hjb_euler Test finite horizon hjb, forward euler
test_finite_horizon_hjb_scaling Finite Horizon
test_pdf_1D_tensor % Test Tensor Form PDF Evolution
test_pdf_2D_tensor % Test Tensor Form PDF Evolution ND
test_pdf_ND_tensor % Test Tensor Form PDF Evolution ND
test_pdf_ND_tensor_run % Test Tensor Form PDF Evolution ND
SOURCE CODE
function res = SRMultV(A,F)
% SRMULTV multiplies a ktensor operators A with a ktensor function F. The
% result is a new ktensor function AF.
% Input:
%   A - ktensor operator.
%   F - ktensor function.
% Output:
%   AB - the product of A and B.
%
% Note:
% The ktensor operator A stores it corresponding matrices as vectors. For
% example, a matrix of size mxm is stored as a vector with m^2 entries.
rA = ncomponents(A);
nd = ndims(F);
LL = F.lambda*A.lambda';
AU = cell(nd,1);
for nn = 1:nd
    N = size(F,nn);
    AU{nn} = blockTransposeV2H(blockTransposeH2V(reshape(A.U{nn},N,N*rA),N)*F.U{nn},N);
end
res = ktensor(LL(:),AU);
res = fixsigns(arrange(res));